// lib/core/localization/app_en.dart
// English strings — সব key ইংরেজিতে

class AppEn {
  AppEn._();

  static const Map<String, String> strings = {
    // Navigation
    'home': 'Home',
    'discover': 'Discover',
    'popular': 'Popular',
    'trending': 'Trending',
    'search': 'Search',
    'videos': 'Videos',
    'notifications': 'Notifications',
    'profile': 'Profile',
    'settings': 'Settings',

    // Auth
    'login': 'Login',
    'register': 'Register',
    'email': 'Email',
    'password': 'Password',
    'forgotPassword': 'Forgot password?',
    'logout': 'Logout',
    'createAccount': 'Create Account',
    'dontHaveAccount': "Don't have an account? Register",
    'alreadyHaveAccount': 'Already have an account? Login',
    'fullName': 'Full Name',
    'nickname': 'Nickname (optional)',
    'bio': 'Bio',

    // Common
    'cancel': 'Cancel',
    'ok': 'OK',
    'yes': 'Yes',
    'no': 'No',
    'save': 'Save',
    'delete': 'Delete',
    'edit': 'Edit',
    'share': 'Share',
    'report': 'Report',
    'retry': 'Retry',
    'loading': 'Loading…',
    'noData': 'Nothing here',
    'copy': 'Copy',
    'copied': 'Copied',
    'seeMore': 'See more',
    'seeLess': 'See less',
    'viewAll': 'View all',
    'clearAll': 'Clear all',
    'confirm': 'Confirm',
    'close': 'Close',

    // Content
    'story': 'Story',
    'novel': 'Novel',
    'video': 'Video',
    'episode': 'Episode',
    'chapter': 'Chapter',
    'read': 'Read',
    'more': 'More',
    'less': 'Less',
    'title': 'Title',
    'description': 'Description',
    'category': 'Category',
    'tags': 'Tags',
    'publish': 'Publish',
    'draft': 'Draft',
    'drafts': 'Drafts',
    'newStory': 'New Story',
    'newNovel': 'New Novel',
    'newVideo': 'New Video',
    'addEpisode': 'Add Episode',
    'readNow': 'Read Now',

    // Social
    'follow': 'Follow',
    'unfollow': 'Unfollow',
    'followers': 'Followers',
    'following': 'Following',
    'comment': 'Comment',
    'comments': 'Comments',
    'reply': 'Reply',
    'like': 'Like',
    'likes': 'Likes',
    'reactions': 'Reactions',
    'writeComment': 'Write a comment…',
    'noComments': 'No comments yet',
    'reaction': 'Reaction',

    // Library
    'download': 'Download',
    'downloaded': 'Downloaded',
    'bookmark': 'Bookmark',
    'saved': 'Saved',
    'offline': 'Offline',
    'fontSize': 'Font size',
    'myWorks': 'My Works',
    'insights': 'Insights',
    'nextEpisode': 'Next episode',
    'prevEpisode': 'Previous episode',

    // Settings
    'theme': 'Theme',
    'language': 'Language',
    'bangla': 'বাংলা',
    'english': 'English',
    'system': 'System',
    'dark': 'Dark',
    'light': 'Light',
    'legal': 'Legal',
    'terms': 'Terms of Use',
    'privacy': 'Privacy Policy',
    'about': 'About',
    'version': 'Version',
    'supportEmail': 'Support Email',
    'deleteAccount': 'Delete Account',
    'deleteAccountConfirm':
        'Your account will be deleted in 7 days. If you login within this time, the deletion will be cancelled. Do you want to continue?',
    'accountDeletionScheduled':
        'Your account will be permanently deleted in 7 days.',
    'logoutConfirm': 'Do you want to logout?',

    // Admin
    'admin': 'Admin',
    'adminDashboard': 'Admin Dashboard',
    'videoFeature': 'Video Feature',
    'openReports': 'Open Reports',
    'statistics': 'Statistics',
    'users': 'Users',
    'thisMonthNew': 'This month (new)',
    'lastMonthNew': 'Last month (new)',
    'totalUsers': 'Total Users',

    // Errors
    'somethingWentWrong': 'Something went wrong',
    'noInternet': 'No internet',
    'tryAgain': 'Try again',
    'loginFailed': 'Login failed',
    'registerFailed': 'Registration failed',
    'saveFailed': 'Save failed',
    'uploadFailed': 'Upload failed',
  };
}
