class AppBn {
  AppBn._();

  static const Map<String, String> strings = {
    'appName': 'গল্পঘর',
    'login': 'লগইন',
    'register': 'রেজিস্টার',
    'email': 'ইমেইল',
    'password': 'পাসওয়ার্ড',
    'forgotPassword': 'পাসওয়ার্ড ভুলে গেছি',
    'logout': 'লগআউট',
    'cancel': 'বাতিল',
    'ok': 'ঠিক আছে',
    'yes': 'হ্যাঁ',
    'no': 'না',
    'save': 'সেভ',
    'delete': 'মুছুন',
    'edit': 'সম্পাদনা',
    'share': 'শেয়ার',
    'report': 'রিপোর্ট',
    'read': 'পড়ুন',
    'more': 'আরও',
    'less': 'কম',
    'follow': 'ফলো',
    'unfollow': 'আনফলো',
    'followers': 'ফলোয়ার',
    'following': 'ফলোয়িং',
    'home': 'হোম',
    'discover': 'আবিষ্কার',
    'popular': 'জনপ্রিয়',
    'trending': 'ট্রেন্ডিং',
    'search': 'সার্চ',
    'videos': 'ভিডিও',
    'notifications': 'নোটিফিকেশন',
    'profile': 'প্রোফাইল',
    'settings': 'সেটিংস',
    'story': 'গল্প',
    'novel': 'উপন্যাস',
    'video': 'ভিডিও',
    'episode': 'পর্ব',
    'comment': 'মন্তব্য',
    'reply': 'উত্তর',
    'like': 'পছন্দ',
    'download': 'ডাউনলোড',
    'downloaded': 'ডাউনলোড হয়েছে',
    'bookmark': 'বুকমার্ক',
    'fontSize': 'লেখার আকার',
    'theme': 'থিম',
    'language': 'ভাষা',
    'bangla': 'বাংলা',
    'english': 'English',
    'dark': 'ডার্ক',
    'light': 'লাইট',
    'system': 'সিস্টেম',
    'loading': 'লোড হচ্ছে…',
    'noData': 'কিছু নেই',
    'retry': 'আবার চেষ্টা',
    'offline': 'অফলাইন',
    'online': 'অনলাইন',
    'noInternet': 'ইন্টারনেট নেই',
    'myWorks': 'আমার লেখা',
    'insights': 'ইনসাইট',
    'saved': 'সংরক্ষিত',
    'drafts': 'খসড়া',
    'admin': 'অ্যাডমিন',
    'legal': 'আইনি',
    'terms': 'শর্তাবলী',
    'privacy': 'প্রাইভেসি',
    'write': 'লিখুন',
    'newStory': 'নতুন গল্প',
    'newNovel': 'নতুন উপন্যাস',
    'newVideo': 'নতুন ভিডিও',
    'publish': 'প্রকাশ',
    'draft': 'খসড়া',
    'category': 'ক্যাটাগরি',
    'title': 'শিরোনাম',
    'description': 'বিবরণ',
    'bio': 'বায়ো',
    'name': 'নাম',
    'username': 'ইউজারনেম',
    'copy': 'কপি',
    'copied': 'কপি হয়েছে',
    'clearAll': 'সব মুছুন',
    'seeMore': 'আরও দেখুন',
    'seeLess': 'কম দেখুন',
    'viewAll': 'সব দেখুন',
    'nextEpisode': 'পরের পর্ব',
    'prevEpisode': 'আগের পর্ব',
  };
}
