// lib/core/localization/app_bn.dart
// বাংলা strings — সব key বাংলায়

class AppBn {
  AppBn._();

  static const Map<String, String> strings = {
    // Navigation
    'home': 'হোম',
    'discover': 'আবিষ্কার',
    'popular': 'জনপ্রিয়',
    'trending': 'ট্রেন্ডিং',
    'search': 'সার্চ',
    'videos': 'ভিডিও',
    'notifications': 'নোটিফিকেশন',
    'profile': 'প্রোফাইল',
    'settings': 'সেটিংস',

    // Auth
    'login': 'লগইন',
    'register': 'রেজিস্টার',
    'email': 'ইমেইল',
    'password': 'পাসওয়ার্ড',
    'forgotPassword': 'পাসওয়ার্ড ভুলে গেছি?',
    'logout': 'লগআউট',
    'createAccount': 'অ্যাকাউন্ট তৈরি করুন',
    'dontHaveAccount': 'অ্যাকাউন্ট নেই? রেজিস্টার করুন',
    'alreadyHaveAccount': 'ইতিমধ্যে অ্যাকাউন্ট আছে? লগইন',
    'fullName': 'পূর্ণ নাম',
    'nickname': 'ডাক নাম (ঐচ্ছিক)',
    'bio': 'বায়ো',

    // Common
    'cancel': 'বাতিল',
    'ok': 'ঠিক আছে',
    'yes': 'হ্যাঁ',
    'no': 'না',
    'save': 'সেভ',
    'delete': 'মুছুন',
    'edit': 'সম্পাদনা',
    'share': 'শেয়ার',
    'report': 'রিপোর্ট',
    'retry': 'আবার চেষ্টা',
    'loading': 'লোড হচ্ছে…',
    'noData': 'কিছু নেই',
    'copy': 'কপি',
    'copied': 'কপি হয়েছে',
    'seeMore': 'আরও দেখুন',
    'seeLess': 'কম দেখুন',
    'viewAll': 'সব দেখুন',
    'clearAll': 'সব মুছুন',
    'confirm': 'নিশ্চিত',
    'close': 'বন্ধ',

    // Content
    'story': 'গল্প',
    'novel': 'উপন্যাস',
    'video': 'ভিডিও',
    'episode': 'পর্ব',
    'chapter': 'অধ্যায়',
    'read': 'পড়ুন',
    'more': 'আরও',
    'less': 'কম',
    'title': 'শিরোনাম',
    'description': 'বিবরণ',
    'category': 'ক্যাটাগরি',
    'tags': 'ট্যাগ',
    'publish': 'প্রকাশ',
    'draft': 'খসড়া',
    'drafts': 'খসড়া',
    'newStory': 'নতুন গল্প',
    'newNovel': 'নতুন উপন্যাস',
    'newVideo': 'নতুন ভিডিও',
    'addEpisode': 'পর্ব যোগ করুন',
    'readNow': 'এখনই পড়ুন',

    // Social
    'follow': 'ফলো',
    'unfollow': 'আনফলো',
    'followers': 'ফলোয়ার',
    'following': 'ফলোয়িং',
    'comment': 'মন্তব্য',
    'comments': 'মন্তব্য',
    'reply': 'উত্তর',
    'like': 'পছন্দ',
    'likes': 'পছন্দ',
    'reactions': 'প্রতিক্রিয়া',
    'writeComment': 'মন্তব্য লিখুন…',
    'noComments': 'এখনো কোনো মন্তব্য নেই',
    'reaction': 'প্রতিক্রিয়া',

    // Library
    'download': 'ডাউনলোড',
    'downloaded': 'ডাউনলোড হয়েছে',
    'bookmark': 'বুকমার্ক',
    'saved': 'সংরক্ষিত',
    'offline': 'অফলাইন',
    'fontSize': 'লেখার আকার',
    'myWorks': 'আমার লেখা',
    'insights': 'ইনসাইট',
    'nextEpisode': 'পরের পর্ব',
    'prevEpisode': 'আগের পর্ব',

    // Settings
    'theme': 'থিম',
    'language': 'ভাষা',
    'bangla': 'বাংলা',
    'english': 'English',
    'system': 'সিস্টেম',
    'dark': 'ডার্ক',
    'light': 'লাইট',
    'legal': 'আইনি',
    'terms': 'ব্যবহারের শর্তাবলী',
    'privacy': 'গোপনীয়তা নীতি',
    'about': 'সম্পর্কে',
    'version': 'ভার্সন',
    'supportEmail': 'সাপোর্ট ইমেইল',
    'deleteAccount': 'অ্যাকাউন্ট ডিলিট করুন',
    'deleteAccountConfirm':
        'আপনার অ্যাকাউন্ট ৭ দিনের মধ্যে মুছে ফেলা হবে। এই সময়ে লগইন করলে বাতিল হয়ে যাবে। আপনি কি চালিয়ে যেতে চান?',
    'accountDeletionScheduled':
        'আপনার অ্যাকাউন্ট ৭ দিন পর সম্পূর্ণ মুছে ফেলা হবে।',
    'logoutConfirm': 'আপনি কি লগআউট করতে চান?',

    // Admin
    'admin': 'অ্যাডমিন',
    'adminDashboard': 'অ্যাডমিন ড্যাশবোর্ড',
    'videoFeature': 'ভিডিও ফিচার',
    'openReports': 'খোলা রিপোর্ট',
    'statistics': 'পরিসংখ্যান',
    'users': 'ইউজার',
    'thisMonthNew': 'এই মাসে নতুন',
    'lastMonthNew': 'গত মাসে নতুন',
    'totalUsers': 'মোট ইউজার',

    // Errors
    'somethingWentWrong': 'কিছু একটা সমস্যা হয়েছে',
    'noInternet': 'ইন্টারনেট নেই',
    'tryAgain': 'আবার চেষ্টা করুন',
    'loginFailed': 'লগইন ব্যর্থ',
    'registerFailed': 'রেজিস্টার ব্যর্থ',
    'saveFailed': 'সেভ ব্যর্থ',
    'uploadFailed': 'আপলোড ব্যর্থ',
  };
}
