class AppEn {
  AppEn._();

  static const Map<String, String> strings = {
    'appName': 'GolpoGhor',
    'login': 'Login',
    'register': 'Register',
    'email': 'Email',
    'password': 'Password',
    'forgotPassword': 'Forgot password?',
    'logout': 'Logout',
    'cancel': 'Cancel',
    'ok': 'OK',
    'yes': 'Yes',
    'no': 'No',
    'save': 'Save',
    'delete': 'Delete',
    'edit': 'Edit',
    'share': 'Share',
    'report': 'Report',
    'read': 'Read',
    'more': 'More',
    'less': 'Less',
    'follow': 'Follow',
    'unfollow': 'Unfollow',
    'followers': 'Followers',
    'following': 'Following',
    'home': 'Home',
    'discover': 'Discover',
    'popular': 'Popular',
    'trending': 'Trending',
    'search': 'Search',
    'videos': 'Videos',
    'notifications': 'Notifications',
    'profile': 'Profile',
    'settings': 'Settings',
    'story': 'Story',
    'novel': 'Novel',
    'video': 'Video',
    'episode': 'Episode',
    'comment': 'Comment',
    'reply': 'Reply',
    'like': 'Like',
    'download': 'Download',
    'downloaded': 'Downloaded',
    'bookmark': 'Bookmark',
    'fontSize': 'Font size',
    'theme': 'Theme',
    'language': 'Language',
    'bangla': 'বাংলা',
    'english': 'English',
    'dark': 'Dark',
    'light': 'Light',
    'system': 'System',
    'loading': 'Loading…',
    'noData': 'Nothing here',
    'retry': 'Retry',
    'offline': 'Offline',
    'online': 'Online',
    'noInternet': 'No internet',
    'myWorks': 'My Works',
    'insights': 'Insights',
    'saved': 'Saved',
    'drafts': 'Drafts',
    'admin': 'Admin',
    'legal': 'Legal',
    'terms': 'Terms',
    'privacy': 'Privacy',
    'write': 'Write',
    'newStory': 'New Story',
    'newNovel': 'New Novel',
    'newVideo': 'New Video',
    'publish': 'Publish',
    'draft': 'Draft',
    'category': 'Category',
    'title': 'Title',
    'description': 'Description',
    'bio': 'Bio',
    'name': 'Name',
    'username': 'Username',
    'copy': 'Copy',
    'copied': 'Copied',
    'clearAll': 'Clear all',
    'seeMore': 'See more',
    'seeLess': 'See less',
    'viewAll': 'View all',
    'nextEpisode': 'Next episode',
    'prevEpisode': 'Previous episode',
  };
}
